### ISSUE TITLE
Cache `gem install fontist`

### ISSUE THREAD

**Issue by jcbhmr** [fontist/setup-fontist#8]
ideally somehow want to avoid the expensive installation that happens. ideal world would be that fontist releases a single binary that we could just download and use but i dont think you can do that with ruby (?)

~~next best thing would be for fontist (or this action) to host a pre-compiled installdir result from `gem install fontist --install-dir /tarballme` for each Windows, macOS, and Linux.~~ not practical 

next best thing after that is to use $RUNNER_TOOL_CACHE and/or workflow cache to cache the result of `gem install fontist --install-dir /somewhere` so that the same user only gets hit with the 1 minute compile time ONCE and then just uses that cache over and over again

**Comment by jcbhmr** [comment]
today i learned... $RUNNER_TOOL_CACHE is relevant ONLY FOR SELF-HOSTED RUNNERS. github.com runners clear the $RUNNER_TOOL_CACHE and re-initialize it with predefined packages/tools each time they get a new job -- this is to avoid cross-contaminating someone else's runner stuff.

so $RUNNER_TOOL_CACHE isn't quite as important as I thought it was. that's an oopsie on me. @CAMOBAP sorry i think i mislead you in our earlier conversation 😬

reference: https://github.com/actions/toolkit/issues/58
and https://github.com/actions/runner-images/discussions/8010

**Comment by ronaldtse** [comment]
It should actually be possible to run Fontist in a standalone manner, through Tebako. @maxirmx does Tebako support Fontist?

**Comment by maxirmx** [comment]
> ideally somehow want to avoid the expensive installation that happens. ideal world would be that fontist releases a single binary that we could just download and use but i dont think you can do that with ruby (?)
> 

We can release fontist cli as a single binary using  [tebako](https://github.com/tamatebako/tebako) gem for Ubuntu/MacOS/Alpine. It is possible that we can use [aibika](https://github.com/tamatebako/aibika) gem for Windows  but it needs testing.

That means creating separate workflow like [packed-mn](https://github.com/metanorma/packed-mn) that will do packaging and release.

It would be nice if someone (not me) does it so that I am able to understand how to improve documentation.

**Comment by maxirmx** [comment]
Using tebako or aibika will also solve possible Ruby installation version issues (ref https://github.com/fontist/setup/issues/5) since Ruby will be packages as well.

**Comment by CAMOBAP** [comment]
> It would be nice if someone (not me) does it so that I am able to understand how to improve documentation.

I think I can help

Maybe we can add this workflow to fontist repo by itself i.e. not create a repo like packed-fontist

@alexeymorozov @ronaldtse @maxirmx any thoughts on organization?

**Comment by ronaldtse** [comment]
@CAMOBAP totally agree about adding the workflow to the Fontist repo itself!

**Comment by CAMOBAP** [comment]
https://github.com/fontist/fontist/issues/356 - reported
